export enum VisibilityLevel {
  PUBLIC_PROFILE = 'PUBLIC_PROFILE',
  TEAM_DISCOVERABLE = 'TEAM_DISCOVERABLE',
  TEAM_PRIVATE = 'TEAM_PRIVATE',
  ORGANIZER_ONLY = 'ORGANIZER_ONLY',
  MENTOR_ONLY = 'MENTOR_ONLY',
}
export enum ExperienceLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
  EXPERT = 'EXPERT',
}
